language: objective-c
osx_image: xcode7.1
sudo: false

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - brew update
    - brew upgrade xctool
    - cd Example && pod update && cd $TRAVIS_BUILD_DIR

script:
    # Travis comes with xctool preinstalled
    - xctool test -workspace Example/Example.xcworkspace -scheme DPMeterViewTests -sdk iphonesimulator
